### PR TITLE
Validate PRs in Github Actions

### PR DESCRIPTION
**Pull request by ulrikstrid**

### CODE REVIEW

**Comment by wokalski** [comment]
@ulrikstrid IIRC the azure scripts have special handling for 4.04 too. I don't remember why 🤦‍♂

**Comment by ulrikstrid** [comment]
It skips 4.04 on Windows, do we need to run it on 4.04 since it's pretty old? Maybe bucklescript's version could be the lower bound?

**Comment by wokalski** [comment]
I think lower bound should be `min` of whatever revery uses or bucklescript

**Comment by wokalski** [comment]
As appealing as github actions are, azure-pipelines (#55) proved to be just too good.

**Comment by wokalski** [comment]
Most notably Github Actions' cache is too limited. 500 megabytes is not enough for esy!

**Pull request closed without merging**
