### PR TITLE
Simple component api

### LINKED ISSUE #28: Allow declaring components on one line
The current dance with:

```reason
let c = component("name");
let somethingElse = (~prop, ~prop, ()) => component(hooks => ...
```

is really annoying. It feels like using something very rough unpolished. We should strive to make possible the following:

```
let somethingElse = component((~prop, ~prop, ()) => ...)
```

### PR DESCRIPTION
**Pull request by wokalski**
Fixes #28 

This PR adds a PPX for component definition:

**Before**:
```reason
module Box = {
  let component = nativeComponent("Box");
  let createElement =
      (~key=?, ~title="ImABox", ~onClick as _=?, ~children as _children, ()) =>
    component(~key?, h =>
      (
        h,
        {
          children: listToElement([]),
          make: () => Implementation.{name: "Box", element: Text(title)},
          configureInstance: (~isFirstRender, instance) =>
            isFirstRender
              ? instance : Implementation.{name: "Box", element: Text(title)},
        },
      )
    );
};
```

**After**:
```reason
module Box = {
  let%nativeComponent make = (~title="ImABox", (), h) => (
    {
      children: listToElement([]),
      make: () => Implementation.{name: "Box", element: Text(title)},
      configureInstance: (~isFirstRender, instance) =>
        isFirstRender
          ? instance : Implementation.{name: "Box", element: Text(title)},
    },
    h
  );
};
```

### CODE REVIEW

**Comment by glennsl** [comment]
Exciting!

Have you considered using

```rust
[@nativeComponent]
let make = ...
```

instead? While perhaps not strictly equivalent, wouldn't this pretty much work the same while also mirroring the new ReasonReact ppx? I also think it reads better, but that might just be familiarity.

**Comment by glennsl** [comment]
What does it translate to? Is it basically the same, just with `Expert.component` and the tuple switched around?

**Comment by wokalski** [comment]
@glennsl it is implemented as both attribute and extension. The attribute will be removed in the future though. It's for supporting `dynamicKeys`. I doubt anyone is using that feature though and it'll be removed with some internal refactor.

I prefer extensions because they clearly indicate which node they are attached to. Attributes are not visually attached to a node.

**Comment by wokalski** [comment]
@glennsl it expands similarly to what you'd expect from `let%bind`. i.e.

```
let%component make = (~prop) => {
  let%hook (state, setState) = Hooks.state("");
  <Text value=state />;
};
```

expands to:

```
let component = Brisk_jsx_runtime.Expert.component("Module.make");
let make = (~prop) => component({
  __brisk_ppx_hooks__ => {
    let ((state, setState), __brisk_ppx_hooks__) = Hooks.state("", __brisk_ppx_hooks__);
  (<Text value=state />, __brisk_ppx_hooks__);
});
```

**Comment by wokalski** [comment]
[This](https://github.com/briskml/brisk-reconciler/pull/42/files#diff-5c40220c82be09b9e62bf6854d8724ddR235-R246) is the most interesting bit in the hook ppx. It checks if there's any hook in any child expression of a let binding. If it's the last one, we wrap the result in the tuple `(element, hooks)`

**Comment by glennsl** [comment]
Oh, neat. So `(element, hooks)` is basically `return` then? Yeah, simple works! And type errors should look basically like they do today.

**Pull request merged**
