### PR TITLE
Et7f3/GitHub actions workflows

### LINKED ISSUE #58: Warn on CI if esy.lock is not up to date
If any of the esy.lock's is not up to date we should warn.

Additionally I'm wondering if it's possible to put all the locks and package-ci-*.jsons in a `ci` directory and have it still work.

### PR DESCRIPTION
**Pull request by Et7f3**
Oups I wanted to rename my branch but I have deleted the old one (and github close the PR #69)

@wokalski Do you want https://github.com/actions/stale ?

Do you want release on new branch is created like on branch name match `*.*.*` launch npm release script ? With a branch per version you can backport easily + it is like dune/ocaml/esy do.

This PR close #58

### CODE REVIEW

**Comment by Et7f3** [comment]
:smiley: All target have `Cache saved successfully` :). I have forgotten to remove 4.04 in azure pipeline. It will be a test to see if cache are really working.

**Comment by wokalski** [comment]
I don’t think we need stale. I understand the benefits of releases on separate branches but I’d rather stick to the simple setup where merging a change with a different version number on master causes npm release.

**Comment by Et7f3** [comment]
Ok so it is ready to merge :). Npm release can also be run on tag creation.

**Comment by wokalski** [comment]
Ok, I think it aged enough to be merged. Just kidding. I'm a bad maintainer but thankfully there are no angry people in this community. Does this remove all things azure, too? I don't think we need it anymore. Great job @Et7f3. You're doing great job.

**Comment by wokalski** [comment]
.azure-pipelines are still in place. Feel free to get rid of them, too!

**Comment by wokalski** [comment]
On second thought, making suggestions to a contributor after months of silence doesn't seem like the best idea, lol. If you don't have time/don't want to now, just let me know and I'll merge as is.

**Comment by wokalski** [comment]
For code archeologists: The reason why I was sceptical initially is that it just worked on azure, azure is (was?) much more generous on the free/OSS plan, and azure is (arguably) more robust. There has been only one technical change (big cache on GA) and multiple UX ones that caused me to reconsider. Azure UI/UX often doesn't work, is slightly confusing and GA are simply a much better fit for an open source project from my experience.

**Comment by Et7f3** [comment]
> Does this remove all things azure, too?

No because you asked https://github.com/briskml/brisk-reconciler/pull/70/commits/8c7c51aeceb028ec9cfcce655ee1031a3678bb75

> On second thought, making suggestions to a contributor after months of silence doesn't seem like the best idea, lol.

Not implemented 🙂.

> azure is (was?) much more generous on the free/OSS plan
> big cache on GA

At the moment the cache limit is 2 GB per repository. It is enough if we just try to compile and run the test on latest ocaml we support (we can even have 4.04 support). If we want to cache and test all version of OCaml/OS the matrix is prettry large and we exceed the cache limit (3 versions x 400 Mo for windows+2 OS x 3 versions x 200Mo for mac/linux). I don't know why windows is heavier but it is too much to drop all azure ci.
So this PR only add linting step. I can bring back  build step but the project will hit a cache miss for at least one os/version.

**Comment by wokalski** [comment]
Thank you for the PR @Et7f3. I'm looking forward to seeing release drafter in action 😄.

**Pull request merged**
